"""Golden-hash parity tests: Python must produce byte-for-byte identical hashes to Rust.

Every expected value below was generated by `cargo run --bin emit_golden` against
the Rust starfix crate *after* PR #11 was merged (commit on 2026-03-20).  The Rust
values are treated as the authoritative source of truth; these tests are regression
guards that will fail immediately if the Python implementation diverges.

Covers 36 distinct Arrow tables / arrays:
  - spec examples A, B, C, D, E, F, G, H, I, J, K, N, O
  - all primitive scalar types (bool, int8..uint64, float32, float64)
  - temporal types (date32, date64, time32(s/ms), time64(us/ns))
  - variable-length (binary, string/utf8)
  - decimal128 (precision ranges 1-9, 10-18, 19-38)
  - list-of-int32
  - struct column, nested struct (two levels), struct with nullable children
  - multi-type record batch, schema-only (empty) hash
  - streaming two-batch incremental update
"""

from __future__ import annotations

from decimal import Decimal

import pyarrow as pa
import pytest
from starfix.arrow_digester import ArrowDigester


# ---------------------------------------------------------------------------
# Spec examples (byte-exact conformance, letter-for-letter from spec)
# ---------------------------------------------------------------------------


class TestSpecExamples:
    def test_example_a_two_column_table(self):
        """Example A: {age: Int32 non-null, name: LargeUtf8 nullable} — two rows."""
        schema = pa.schema([
            pa.field("age", pa.int32(), nullable=False),
            pa.field("name", pa.large_utf8(), nullable=True),
        ])
        batch = pa.record_batch(
            {
                "age": pa.array([25, 30], type=pa.int32()),
                "name": pa.array(["Alice", None], type=pa.large_utf8()),
            },
            schema=schema,
        )
        result = ArrowDigester.hash_record_batch(batch).hex()
        assert result == "0000018020e47f4462f26b0bc73ad110ea0f9198c2745c04ce23335093d2b78ef51c88"

    def test_example_b_bool_array_with_nulls(self):
        """Example B: BooleanArray [true, NULL, false, true]."""
        array = pa.array([True, None, False, True], type=pa.bool_())
        result = ArrowDigester.hash_array(array).hex()
        assert result == "00000185a9c99eba7bcfd9b14fd529b9534f2289319779270aa4a072f117cf90a6ac8b"

    def test_example_c_non_nullable_int32(self):
        """Example C: Int32Array [1, 2, 3] — non-nullable."""
        array = pa.array([1, 2, 3], type=pa.int32())
        result = ArrowDigester.hash_array(array).hex()
        assert result == "00000109cb203c0cae27346ea2ce37d1245775ac99c8b26634677de56268ba01dc693c"

    def test_example_d_non_nullable_binary(self):
        """Example D: BinaryArray [b'hi', b''] — non-nullable; tests Binary→LargeBinary canonicalization."""
        array = pa.array([b"hi", b""], type=pa.binary())
        result = ArrowDigester.hash_array(array).hex()
        assert result == "0000010fbc627fc7ad9d5f2e96fec8fa57b56b364a04a8af7e374015a07b26bd1ac80d"

    def test_example_e_column_order_independence(self):
        """Example E: columns [x: Int32, y: Boolean nullable] — order must not matter."""
        schema_xy = pa.schema([
            pa.field("x", pa.int32(), nullable=False),
            pa.field("y", pa.bool_(), nullable=True),
        ])
        schema_yx = pa.schema([
            pa.field("y", pa.bool_(), nullable=True),
            pa.field("x", pa.int32(), nullable=False),
        ])
        batch_xy = pa.record_batch(
            {"x": pa.array([10], type=pa.int32()), "y": pa.array([True], type=pa.bool_())},
            schema=schema_xy,
        )
        batch_yx = pa.record_batch(
            {"y": pa.array([True], type=pa.bool_()), "x": pa.array([10], type=pa.int32())},
            schema=schema_yx,
        )
        expected = "000001f68bf6319f8ec4aa938e52dd911974348289fbdfb9b5ebed5e14e239a6d8a3a9"
        assert ArrowDigester.hash_record_batch(batch_xy).hex() == expected
        assert ArrowDigester.hash_record_batch(batch_yx).hex() == expected

    def test_example_f_utf8_equivalence(self):
        """Example F: Utf8 and LargeUtf8 arrays with the same data must hash identically."""
        small = pa.array(["ab"], type=pa.utf8())
        large = pa.array(["ab"], type=pa.large_utf8())
        expected = "000001f14d076ffc02533c6560f867b86cde7e15b1a0ac5a892b53697a609191cf307f"
        assert ArrowDigester.hash_array(small).hex() == expected
        assert ArrowDigester.hash_array(large).hex() == expected

    def test_example_g_nullable_int32(self):
        """Example G: Int32Array [Some(42), None, Some(-7), Some(0)]."""
        array = pa.array([42, None, -7, 0], type=pa.int32())
        result = ArrowDigester.hash_array(array).hex()
        assert result == "0000018330f9b8796b9434cbf7bc028c18c58a2a739b980acf9995ce1e5d60b43b0138"

    def test_example_h_nullable_string(self):
        """Example H: StringArray [Some('hello'), None, Some('world'), Some('')]."""
        array = pa.array(["hello", None, "world", ""], type=pa.utf8())
        result = ArrowDigester.hash_array(array).hex()
        assert result == "0000016255bde0141ebf26e08c31c96f6112e5e21d101ab8bb90d77f2c3eec02c62d3c"

    def test_example_i_empty_table(self):
        """Example I: schema {a: Int32 non-null, b: Boolean nullable} with zero rows."""
        schema = pa.schema([
            pa.field("a", pa.int32(), nullable=False),
            pa.field("b", pa.bool_(), nullable=True),
        ])
        digester = ArrowDigester(schema)
        result = digester.finalize().hex()
        assert result == "000001df8887d2ebb6968ba1dd994b1c663e0539f218f6045996a03dd20209c40d0922"

    def test_example_j_multi_batch_streaming(self):
        """Example J: batch-split independence — two batches == one combined batch."""
        schema = pa.schema([pa.field("v", pa.int32(), nullable=False)])
        batch1 = pa.record_batch({"v": pa.array([1, 2], type=pa.int32())}, schema=schema)
        batch2 = pa.record_batch({"v": pa.array([3], type=pa.int32())}, schema=schema)
        digester = ArrowDigester(schema)
        digester.update(batch1)
        digester.update(batch2)
        result = digester.finalize().hex()
        assert result == "000001d4efb209fd319c8b418662caad5922b154003d0425fa722060b44e6d5eb0d857"

    def test_example_k_struct_column(self):
        """Example K: {person: Struct<age: Int32 non-null, name: LargeUtf8 non-null>}."""
        person_type = pa.struct([
            pa.field("age", pa.int32(), nullable=False),
            pa.field("name", pa.large_utf8(), nullable=False),
        ])
        schema = pa.schema([pa.field("person", person_type, nullable=False)])
        person_col = pa.array(
            [{"age": 25, "name": "Alice"}, {"age": 30, "name": "Bob"}],
            type=person_type,
        )
        batch = pa.record_batch({"person": person_col}, schema=schema)
        result = ArrowDigester.hash_record_batch(batch).hex()
        assert result == "000001e3516302d68fd1fc4860fa4b7e0d4a6d60d500a9d7ccae79e445c5980021e4ec"

    def test_example_n_list_of_struct(self):
        """Example N: {items: LargeList<Struct<id: Int32, label: LargeUtf8>> nullable}.

        Row 0: [{id:1, label:'a'}, {id:2, label:'b'}]
        Row 1: [{id:3, label:'c'}]
        """
        item_type = pa.struct([
            pa.field("id", pa.int32(), nullable=False),
            pa.field("label", pa.large_utf8(), nullable=False),
        ])
        schema = pa.schema([
            pa.field("items", pa.large_list(pa.field("item", item_type, nullable=False)), nullable=True)
        ])
        items_col = pa.array(
            [
                [{"id": 1, "label": "a"}, {"id": 2, "label": "b"}],
                [{"id": 3, "label": "c"}],
            ],
            type=pa.large_list(pa.field("item", item_type, nullable=False)),
        )
        batch = pa.record_batch({"items": items_col}, schema=schema)
        result = ArrowDigester.hash_record_batch(batch).hex()
        assert result == "0000019c9cc6230a42e646a475ec1c8125fe396dcace351d64ff6e63e8f53d329c4895"

    def test_example_o_nested_struct(self):
        """Example O: {s: Struct<a: Int32, nested: Struct<p: Int32, q: Int32>>} — two levels."""
        nested_type = pa.struct([
            pa.field("p", pa.int32(), nullable=False),
            pa.field("q", pa.int32(), nullable=False),
        ])
        outer_type = pa.struct([
            pa.field("a", pa.int32(), nullable=False),
            pa.field("nested", nested_type, nullable=False),
        ])
        schema = pa.schema([pa.field("s", outer_type, nullable=False)])
        s_col = pa.array(
            [{"a": 10, "nested": {"p": 20, "q": 30}}],
            type=outer_type,
        )
        batch = pa.record_batch({"s": s_col}, schema=schema)
        result = ArrowDigester.hash_record_batch(batch).hex()
        assert result == "000001e732b8458782d9a331722698883617eec7cd1492028947b4ce3e97c7d6201550"


# ---------------------------------------------------------------------------
# Primitive scalar types (all 11 numeric/bool types)
# ---------------------------------------------------------------------------


class TestPrimitiveTypes:
    def test_bool(self):
        array = pa.array([True, False, None, True], type=pa.bool_())
        result = ArrowDigester.hash_array(array).hex()
        assert result == "000001e752bea45ed48352e104fb24919ea68b1af64281231aff3a52b51a5fcabe7fb1"

    def test_int8(self):
        array = pa.array([1, None, -1, 127], type=pa.int8())
        result = ArrowDigester.hash_array(array).hex()
        assert result == "0000019ab12c5c219df0b745b77bb592945dfd5a8d8bf6c20752cb601cc554bde708bc"

    def test_int16(self):
        array = pa.array([1000, None, -1000, 32767], type=pa.int16())
        result = ArrowDigester.hash_array(array).hex()
        assert result == "00000163dac968f9f62a036126abe3e53404b69a40f2cf02872a1fc970c7428c5869b4"

    def test_int32(self):
        array = pa.array([42, None, -7, 0], type=pa.int32())
        result = ArrowDigester.hash_array(array).hex()
        assert result == "0000018330f9b8796b9434cbf7bc028c18c58a2a739b980acf9995ce1e5d60b43b0138"

    def test_int64(self):
        array = pa.array([1_000_000, None, -1_000_000, 0], type=pa.int64())
        result = ArrowDigester.hash_array(array).hex()
        assert result == "000001950cf62cd41a3cfb936bcaeb2af16e4b9010e72e6201af4755c016b7b9466acf"

    def test_uint8(self):
        array = pa.array([0, 1, None, 255], type=pa.uint8())
        result = ArrowDigester.hash_array(array).hex()
        assert result == "00000130328e5fa11093ea36a10554afdb07fa718453f41a113dbdbdefc5baf06d1ffd"

    def test_uint16(self):
        array = pa.array([0, 1000, None, 65535], type=pa.uint16())
        result = ArrowDigester.hash_array(array).hex()
        assert result == "00000133e15d7b6d806f8c121f9683e1f6b62674b0f48710f7f6dc3155262e0fc84357"

    def test_uint32(self):
        array = pa.array([0, 1_000_000, None, 4_294_967_295], type=pa.uint32())
        result = ArrowDigester.hash_array(array).hex()
        assert result == "000001c3d60c88f4842be618c85a09d604cbc0d87d8ea27c164fc2acb387ca50bbfa2e"

    def test_uint64(self):
        array = pa.array([0, 1_000_000_000, None, 18_446_744_073_709_551_615], type=pa.uint64())
        result = ArrowDigester.hash_array(array).hex()
        assert result == "00000144997caad273e039ba4919a2f1db91f05b6546271121619bb1fc97d8757f180b"

    def test_float32(self):
        array = pa.array([1.5, None, -3.14, 0.0], type=pa.float32())
        result = ArrowDigester.hash_array(array).hex()
        assert result == "000001f5c04a8a43027a04f68de9f71b99b3075459c9c296f68aecdc92bac8ef506baa"

    def test_float64(self):
        array = pa.array([1.5, None, -3.14, 0.0], type=pa.float64())
        result = ArrowDigester.hash_array(array).hex()
        assert result == "000001b0e2b1cc3668a42dbc98d3b7246f7e8cdf2d5e6a38cc0510e463d36cbeecff0b"


# ---------------------------------------------------------------------------
# Temporal types
# ---------------------------------------------------------------------------


class TestTemporalTypes:
    def test_date32(self):
        """Date32: days since Unix epoch."""
        array = pa.array([0, 18993, None, -1], type=pa.date32())
        result = ArrowDigester.hash_array(array).hex()
        assert result == "000001103053df817a93502fae8bd8d052c57e48acc76fc65db9316c2425805f2f7ef6"

    def test_date64(self):
        """Date64: ms since Unix epoch."""
        array = pa.array([0, 1_640_995_200_000, None, -86_400_000], type=pa.date64())
        result = ArrowDigester.hash_array(array).hex()
        assert result == "00000106dde92a47a5a0db64ce2c83c1de96868b8f55868003fb6e894be0751d10beeb"

    def test_time32_seconds(self):
        """Time32(s): seconds since midnight."""
        array = pa.array([1000, None, 5000, 0], type=pa.time32("s"))
        result = ArrowDigester.hash_array(array).hex()
        assert result == "000001aba70469e596c735ec13c3d60a9db2d0e5515eb864f07ad5d24572b35f23eacc"

    def test_time32_milliseconds(self):
        """Time32(ms): milliseconds since midnight."""
        array = pa.array([1_000_000, None, 5_000_000, 0], type=pa.time32("ms"))
        result = ArrowDigester.hash_array(array).hex()
        assert result == "000001abd6f51bd0ca68584a4ae73f4f9351cfe97fe6f3f85ed315f9b3628650a97564"

    def test_time64_microseconds(self):
        """Time64(us): microseconds since midnight."""
        array = pa.array([1_000_000, None, 5_000_000, 0], type=pa.time64("us"))
        result = ArrowDigester.hash_array(array).hex()
        assert result == "000001c96d705b1278f9ffe1b31fb307408768f14d961c44028a1d0f778dd61786ee26"

    def test_time64_nanoseconds(self):
        """Time64(ns): nanoseconds since midnight."""
        array = pa.array([1_000_000_000, None, 5_000_000_000, 0], type=pa.time64("ns"))
        result = ArrowDigester.hash_array(array).hex()
        assert result == "0000013236ab3ffd9de453dc2a7613731108b132583249f2d42eb7a102dd430e66175f"


# ---------------------------------------------------------------------------
# Variable-length types
# ---------------------------------------------------------------------------


class TestVariableLengthTypes:
    def test_binary(self):
        """Binary array — tests LargeBinary canonicalization."""
        array = pa.array([b"hello", None, b"world", b""], type=pa.binary())
        result = ArrowDigester.hash_array(array).hex()
        assert result == "0000018dc3a0e479d1335553546c8f23c36d75335cbd34805a6f96c5d5225b347fbc57"

    def test_large_binary_equals_binary(self):
        """LargeBinary and Binary arrays with same data must produce the same hash."""
        small = pa.array([b"hello", None, b"world", b""], type=pa.binary())
        large = pa.array([b"hello", None, b"world", b""], type=pa.large_binary())
        expected = "0000018dc3a0e479d1335553546c8f23c36d75335cbd34805a6f96c5d5225b347fbc57"
        assert ArrowDigester.hash_array(small).hex() == expected
        assert ArrowDigester.hash_array(large).hex() == expected

    def test_string(self):
        """String (Utf8) array — tests LargeUtf8 canonicalization."""
        array = pa.array(["hello", None, "world", ""], type=pa.utf8())
        result = ArrowDigester.hash_array(array).hex()
        assert result == "0000016255bde0141ebf26e08c31c96f6112e5e21d101ab8bb90d77f2c3eec02c62d3c"

    def test_large_string_equals_string(self):
        """LargeUtf8 and Utf8 arrays with same data must produce the same hash."""
        small = pa.array(["hello", None, "world", ""], type=pa.utf8())
        large = pa.array(["hello", None, "world", ""], type=pa.large_utf8())
        expected = "0000016255bde0141ebf26e08c31c96f6112e5e21d101ab8bb90d77f2c3eec02c62d3c"
        assert ArrowDigester.hash_array(small).hex() == expected
        assert ArrowDigester.hash_array(large).hex() == expected


# ---------------------------------------------------------------------------
# Decimal types (precision routing: 1-9, 10-18, 19-38)
# ---------------------------------------------------------------------------


class TestDecimalTypes:
    def test_decimal_precision_9_scale_2(self):
        """Decimal128 precision=9 (maps to decimal32 storage range) scale=2.

        Rust stores raw i128 values [123, -456, 0]. In PyArrow, pa.decimal128(9, 2)
        interprets values as scaled decimals, so we use Decimal strings to get
        the same raw integer storage: 1.23 * 10^2 = 123, etc.
        """
        array = pa.array(
            [Decimal("1.23"), None, Decimal("-4.56"), Decimal("0.00")],
            type=pa.decimal128(9, 2),
        )
        result = ArrowDigester.hash_array(array).hex()
        assert result == "0000014f015bd5c4b6ce6e939a8c890333f3e110c2c28ef8014aafd352f8373791e547"

    def test_decimal_precision_15_scale_3(self):
        """Decimal128 precision=15 (maps to decimal64 range) scale=3."""
        array = pa.array(
            [Decimal("1234567890.123"), None, Decimal("-9876543.210"), Decimal("0.000")],
            type=pa.decimal128(15, 3),
        )
        result = ArrowDigester.hash_array(array).hex()
        assert result == "000001dc08c7b9c583edecec36bc5dee21cd2edec9f402a651014fea5f8834d16ad737"

    def test_decimal_precision_38_scale_5(self):
        """Decimal128 precision=38 scale=5 — full 16-byte integer path."""
        array = pa.array(
            [
                Decimal("1234567890123456789012.34567"),
                None,
                Decimal("-9876543210987654321098.76543"),
                Decimal("0.00000"),
            ],
            type=pa.decimal128(38, 5),
        )
        result = ArrowDigester.hash_array(array).hex()
        assert result == "0000011e3b33d28771b3593fd5dc4b68af8091a1ba9cd493ade374e7368e213bef244e"


# ---------------------------------------------------------------------------
# List types
# ---------------------------------------------------------------------------


class TestListTypes:
    def test_list_of_int32(self):
        """List<Int32> — tests LargeList canonicalization and per-element length prefix."""
        array = pa.array(
            [
                [1, 2, 3],
                None,
                [4, 5],
                [6],
            ],
            type=pa.list_(pa.field("item", pa.int32(), nullable=True)),
        )
        result = ArrowDigester.hash_array(array).hex()
        assert result == "000001dc359d563a1ed210eb271b314612ea8343f0a0b0955b9053a9eb47962d27163c"

    def test_large_list_equals_list(self):
        """LargeList<Int32> with the same data must produce the same hash as List<Int32>."""
        small = pa.array(
            [[1, 2, 3], None, [4, 5], [6]],
            type=pa.list_(pa.field("item", pa.int32(), nullable=True)),
        )
        large = pa.array(
            [[1, 2, 3], None, [4, 5], [6]],
            type=pa.large_list(pa.field("item", pa.int32(), nullable=True)),
        )
        expected = "000001dc359d563a1ed210eb271b314612ea8343f0a0b0955b9053a9eb47962d27163c"
        assert ArrowDigester.hash_array(small).hex() == expected
        assert ArrowDigester.hash_array(large).hex() == expected


# ---------------------------------------------------------------------------
# Struct types
# ---------------------------------------------------------------------------


class TestStructTypes:
    def test_struct_with_nullable_children(self):
        """Non-nullable struct column {a: Int32 non-null, b: Boolean nullable}."""
        struct_type = pa.struct([
            pa.field("a", pa.int32(), nullable=False),
            pa.field("b", pa.bool_(), nullable=True),
        ])
        schema = pa.schema([pa.field("s", struct_type, nullable=False)])
        s_col = pa.array(
            [{"a": 1, "b": True}, {"a": 2, "b": False}, {"a": 3, "b": None}],
            type=struct_type,
        )
        batch = pa.record_batch({"s": s_col}, schema=schema)
        result = ArrowDigester.hash_record_batch(batch).hex()
        assert result == "0000015f1992c5f9130aaa64aa1360e53ddd00b427855ae02e380f534a629353135680"

    def test_struct_field_order_independence(self):
        """Struct fields in different order must hash identically (order-independence)."""
        type_ab = pa.struct([
            pa.field("a", pa.int32(), nullable=False),
            pa.field("b", pa.bool_(), nullable=True),
        ])
        type_ba = pa.struct([
            pa.field("b", pa.bool_(), nullable=True),
            pa.field("a", pa.int32(), nullable=False),
        ])
        schema_ab = pa.schema([pa.field("s", type_ab, nullable=False)])
        schema_ba = pa.schema([pa.field("s", type_ba, nullable=False)])

        data_ab = pa.array(
            [{"a": 1, "b": True}, {"a": 2, "b": False}, {"a": 3, "b": None}],
            type=type_ab,
        )
        data_ba = pa.array(
            [{"b": True, "a": 1}, {"b": False, "a": 2}, {"b": None, "a": 3}],
            type=type_ba,
        )
        batch_ab = pa.record_batch({"s": data_ab}, schema=schema_ab)
        batch_ba = pa.record_batch({"s": data_ba}, schema=schema_ba)
        assert (
            ArrowDigester.hash_record_batch(batch_ab)
            == ArrowDigester.hash_record_batch(batch_ba)
        )


# ---------------------------------------------------------------------------
# Multi-type record batch
# ---------------------------------------------------------------------------


class TestMultiTypeBatch:
    def test_multi_type_record_batch(self):
        """One-row record batch covering all scalar and collection types."""
        schema = pa.schema([
            pa.field("bool", pa.bool_(), nullable=True),
            pa.field("int8", pa.int8(), nullable=False),
            pa.field("uint8", pa.uint8(), nullable=False),
            pa.field("int16", pa.int16(), nullable=False),
            pa.field("uint16", pa.uint16(), nullable=False),
            pa.field("int32", pa.int32(), nullable=False),
            pa.field("uint32", pa.uint32(), nullable=False),
            pa.field("int64", pa.int64(), nullable=False),
            pa.field("uint64", pa.uint64(), nullable=False),
            pa.field("float32", pa.float32(), nullable=False),
            pa.field("float64", pa.float64(), nullable=False),
            pa.field("date32", pa.date32(), nullable=False),
            pa.field("date64", pa.date64(), nullable=False),
            pa.field("time32_second", pa.time32("s"), nullable=False),
            pa.field("time32_millis", pa.time32("ms"), nullable=False),
            pa.field("time64_micro", pa.time64("us"), nullable=False),
            pa.field("time64_nano", pa.time64("ns"), nullable=False),
            pa.field("binary", pa.binary(), nullable=True),
            pa.field("large_binary", pa.large_binary(), nullable=True),
            pa.field("utf8", pa.utf8(), nullable=True),
            pa.field("large_utf8", pa.large_utf8(), nullable=True),
            pa.field("list", pa.list_(pa.field("item", pa.int32(), nullable=True)), nullable=True),
            pa.field("large_list", pa.large_list(pa.field("item", pa.int32(), nullable=True)), nullable=True),
            pa.field("decimal128", pa.decimal128(38, 5), nullable=True),
        ])
        batch = pa.record_batch(
            {
                "bool": pa.array([True], type=pa.bool_()),
                "int8": pa.array([1], type=pa.int8()),
                "uint8": pa.array([1], type=pa.uint8()),
                "int16": pa.array([100], type=pa.int16()),
                "uint16": pa.array([100], type=pa.uint16()),
                "int32": pa.array([1000], type=pa.int32()),
                "uint32": pa.array([1000], type=pa.uint32()),
                "int64": pa.array([100_000], type=pa.int64()),
                "uint64": pa.array([100_000], type=pa.uint64()),
                "float32": pa.array([1.5], type=pa.float32()),
                "float64": pa.array([1.5], type=pa.float64()),
                "date32": pa.array([18993], type=pa.date32()),
                "date64": pa.array([1_640_995_200_000], type=pa.date64()),
                "time32_second": pa.array([3600], type=pa.time32("s")),
                "time32_millis": pa.array([3_600_000], type=pa.time32("ms")),
                "time64_micro": pa.array([3_600_000_000], type=pa.time64("us")),
                "time64_nano": pa.array([3_600_000_000_000], type=pa.time64("ns")),
                "binary": pa.array([b"data1"], type=pa.binary()),
                "large_binary": pa.array([b"large1"], type=pa.large_binary()),
                "utf8": pa.array(["text1"], type=pa.utf8()),
                "large_utf8": pa.array(["large_text1"], type=pa.large_utf8()),
                "list": pa.array([[1, 2]], type=pa.list_(pa.field("item", pa.int32(), nullable=True))),
                "large_list": pa.array([[5, 6]], type=pa.large_list(pa.field("item", pa.int32(), nullable=True))),
                "decimal128": pa.array(
                    [Decimal("1234567890123456789012345.67890")],
                    type=pa.decimal128(38, 5),
                ),
            },
            schema=schema,
        )
        result = ArrowDigester.hash_record_batch(batch).hex()
        assert result == "0000010f8bb471cb34975f20c4b221abff1a90b2d98f24217a2257e3298ee3d4e9f9c4"

    def test_multi_type_schema_only(self):
        """Empty (no-rows) digester over the large multi-type schema."""
        schema = pa.schema([
            pa.field("bool", pa.bool_(), nullable=True),
            pa.field("int8", pa.int8(), nullable=False),
            pa.field("uint8", pa.uint8(), nullable=False),
            pa.field("int16", pa.int16(), nullable=False),
            pa.field("uint16", pa.uint16(), nullable=False),
            pa.field("int32", pa.int32(), nullable=False),
            pa.field("uint32", pa.uint32(), nullable=False),
            pa.field("int64", pa.int64(), nullable=False),
            pa.field("uint64", pa.uint64(), nullable=False),
            pa.field("float32", pa.float32(), nullable=False),
            pa.field("float64", pa.float64(), nullable=False),
            pa.field("date32", pa.date32(), nullable=False),
            pa.field("date64", pa.date64(), nullable=False),
            pa.field("time32_second", pa.time32("s"), nullable=False),
            pa.field("time32_millis", pa.time32("ms"), nullable=False),
            pa.field("time64_micro", pa.time64("us"), nullable=False),
            pa.field("time64_nano", pa.time64("ns"), nullable=False),
            pa.field("binary", pa.binary(), nullable=True),
            pa.field("large_binary", pa.large_binary(), nullable=True),
            pa.field("utf8", pa.utf8(), nullable=True),
            pa.field("large_utf8", pa.large_utf8(), nullable=True),
            pa.field("list", pa.list_(pa.field("item", pa.int32(), nullable=True)), nullable=True),
            pa.field("large_list", pa.large_list(pa.field("item", pa.int32(), nullable=True)), nullable=True),
            pa.field("decimal128", pa.decimal128(38, 5), nullable=True),
        ])
        result = ArrowDigester(schema).finalize().hex()
        assert result == "0000010e62b3f3317d25413b7a4dc6e7a8a6e7c73a73c513cdbe9f9b1f5e5ec56f0e94"


# ---------------------------------------------------------------------------
# Streaming / incremental hashing
# ---------------------------------------------------------------------------


class TestStreamingHashing:
    def test_streaming_two_batches(self):
        """Two-batch incremental update must match the known Rust hash."""
        schema = pa.schema([
            pa.field("uids", pa.int32(), nullable=False),
            pa.field("flags", pa.bool_(), nullable=True),
        ])
        batch1 = pa.record_batch(
            {
                "uids": pa.array([1, 2, 3, 4], type=pa.int32()),
                "flags": pa.array([True, False, None, True], type=pa.bool_()),
            },
            schema=schema,
        )
        batch2 = pa.record_batch(
            {
                "uids": pa.array([5, 6, 7, 8], type=pa.int32()),
                "flags": pa.array([False, True, True, None], type=pa.bool_()),
            },
            schema=schema,
        )
        digester = ArrowDigester(schema)
        digester.update(batch1)
        digester.update(batch2)
        result = digester.finalize().hex()
        assert result == "0000019f5fa370d315a4b4f2314be7b7284a0549b70ad4e21e584fdebf441ad02f44f0"

    def test_batch_split_independence(self):
        """Splitting a batch into two must not change the hash."""
        schema = pa.schema([
            pa.field("v", pa.int32(), nullable=False),
        ])
        combined = pa.record_batch({"v": pa.array([1, 2, 3], type=pa.int32())}, schema=schema)
        batch1 = pa.record_batch({"v": pa.array([1, 2], type=pa.int32())}, schema=schema)
        batch2 = pa.record_batch({"v": pa.array([3], type=pa.int32())}, schema=schema)

        hash_combined = ArrowDigester.hash_record_batch(combined)

        digester = ArrowDigester(schema)
        digester.update(batch1)
        digester.update(batch2)
        hash_split = digester.finalize()

        assert hash_combined == hash_split
