"""Cross-language golden-hash parity tests for include_metadata vectors (PLT-1735).

Every expected hash in `tests/golden/include_metadata_v0.3.json` was generated by
`cargo run --bin emit_golden_metadata` in the Rust starfix crate and is treated as
the authoritative source of truth. These tests will fail immediately if the Python
implementation diverges from Rust.

Covers 9 vectors:
  - no_metadata_include_false        (regression: same as v0.1.0 schema hash)
  - schema_level_metadata            (schema-level metadata, include_metadata=True)
  - field_metadata_single_field      (single field with metadata, include_metadata=True)
  - field_metadata_multiple_fields   (two fields with metadata, include_metadata=True)
  - schema_and_field_metadata        (both schema- and field-level, include_metadata=True)
  - unicode_metadata                 (emoji + CJK keys/values, include_metadata=True)
  - key_reorder_canonical            (metadata keys in alphabetical order)
  - key_reorder_shuffled             (same keys, different insertion order — same hash)
  - empty_metadata_invariant         (no metadata — hash must be same for both flag values)
"""
from __future__ import annotations

import base64
import io
import json
from pathlib import Path
from typing import Any

import pyarrow as pa
import pytest

from starfix.arrow_digester import ArrowDigester

_FIXTURE_PATH = Path(__file__).parent / "golden" / "include_metadata_v0.3.json"


def _load_vectors() -> list[dict[str, Any]]:
    with _FIXTURE_PATH.open() as f:
        return json.load(f)["vectors"]


def _get_vector(vector_id: str) -> dict[str, Any]:
    for v in _load_vectors():
        if v["id"] == vector_id:
            return v
    raise KeyError(f"Vector '{vector_id}' not found in fixture")


def _deserialize_ipc(ipc_b64: str) -> tuple[pa.Schema, pa.RecordBatch | None]:
    raw = base64.b64decode(ipc_b64)
    reader = pa.ipc.open_stream(io.BytesIO(raw))
    schema = reader.schema
    batches = list(reader)
    batch = batches[0] if batches else None
    return schema, batch


@pytest.mark.parametrize("vector", _load_vectors(), ids=lambda v: v["id"])
def test_golden_vector(vector: dict[str, Any]) -> None:
    """Each vector must produce the Rust-authoritative expected_hash."""
    schema, batch = _deserialize_ipc(vector["ipc_b64"])
    include_metadata: bool = vector["include_metadata"]

    if vector["method"] == "hash_schema":
        result = ArrowDigester.hash_schema(schema, include_metadata=include_metadata)
    elif vector["method"] == "hash_record_batch":
        assert batch is not None, (
            f"Vector '{vector['id']}': method is hash_record_batch but IPC has no batch"
        )
        result = ArrowDigester.hash_record_batch(batch, include_metadata=include_metadata)
    else:
        pytest.fail(f"Vector '{vector['id']}': unknown method '{vector['method']}'")

    assert result.hex() == vector["expected_hash"], (
        f"Vector '{vector['id']}' mismatch: {vector['description']}\n"
        f"  got:      {result.hex()}\n"
        f"  expected: {vector['expected_hash']}"
    )


def test_empty_metadata_invariant_both_flags() -> None:
    """Empty-metadata invariant: include_metadata=True must produce the same hash as False."""
    vector = _get_vector("empty_metadata_invariant")
    schema, _ = _deserialize_ipc(vector["ipc_b64"])

    hash_false = ArrowDigester.hash_schema(schema, include_metadata=False).hex()
    hash_true = ArrowDigester.hash_schema(schema, include_metadata=True).hex()

    assert hash_false == vector["expected_hash"], (
        f"empty_metadata_invariant: include_metadata=False got {hash_false}, "
        f"expected {vector['expected_hash']}"
    )
    assert hash_true == vector["expected_hash"], (
        f"empty_metadata_invariant: include_metadata=True got {hash_true}, "
        f"expected {vector['expected_hash']}"
    )
    assert hash_false == hash_true, (
        "empty_metadata_invariant: both flag values must produce the same hash"
    )


def test_key_reorder_hashes_are_identical() -> None:
    """key_reorder_canonical and key_reorder_shuffled must share the same expected_hash."""
    canonical = _get_vector("key_reorder_canonical")
    shuffled = _get_vector("key_reorder_shuffled")

    schema_c, _ = _deserialize_ipc(canonical["ipc_b64"])
    schema_s, _ = _deserialize_ipc(shuffled["ipc_b64"])

    hash_c = ArrowDigester.hash_schema(schema_c, include_metadata=True).hex()
    hash_s = ArrowDigester.hash_schema(schema_s, include_metadata=True).hex()

    assert hash_c == canonical["expected_hash"], (
        f"key_reorder_canonical live hash drifted from fixture"
    )
    assert hash_s == shuffled["expected_hash"], (
        f"key_reorder_shuffled live hash drifted from fixture"
    )
    assert hash_c == hash_s, (
        "key_reorder_canonical and key_reorder_shuffled must have identical hashes\n"
        f"  canonical: {hash_c}\n"
        f"  shuffled:  {hash_s}"
    )
