"""Golden-hash parity tests — Round 2.

Every expected value below was generated by `cargo run --bin emit_golden` against
the Rust starfix crate.  The Rust values are treated as the authoritative source
of truth; these tests are regression guards that will fail immediately if the
Python implementation diverges.

Covers 40+ distinct Arrow tables / arrays across categories:
  - Empty arrays (0 elements)
  - All-null arrays
  - Large boolean arrays (multi-byte bitvec)
  - Single-element arrays
  - Nullable structs (struct itself nullable, hash_array & record batch)
  - Three-level nested structs
  - Struct with list child
  - List<Struct>, nullable List<Struct>
  - List<Struct> with nullable vs non-nullable item field (PLT-1048 edge case)
  - Non-nullable lists
  - Mixed-type structs
  - Mixed struct+list record batches
  - Empty record batches (schema only)
  - All-null columns in batches
  - Unicode strings
  - Binary with varied sizes
  - Struct field order independence
  - Nested struct with nullable inner struct
  - List-of-list (nested lists)
  - Large schema hashes
  - Multi-batch streaming with structs and lists
  - Float special values (NaN, Inf)
  - Realistic batch (struct + list + scalar)
"""

from __future__ import annotations

import pyarrow as pa
import pytest
from starfix.arrow_digester import ArrowDigester


# ---------------------------------------------------------------------------
# Empty arrays
# ---------------------------------------------------------------------------


class TestEmptyArrays:
    def test_empty_int32_array(self):
        """Empty Int32 array (0 elements)."""
        array = pa.array([], type=pa.int32())
        result = ArrowDigester.hash_array(array).hex()
        assert result == "0000015b41cb9aa8a4c79da8859ae00ce976d8184bdf5426060292b69717c6f28ed38a"

    def test_empty_bool_array(self):
        """Empty Boolean array (0 elements)."""
        array = pa.array([], type=pa.bool_())
        result = ArrowDigester.hash_array(array).hex()
        assert result == "000001b93f053f60f756b3d47a304889daa8011b9d09b4c83efbfe10ca7f073d59d4ea"


# ---------------------------------------------------------------------------
# All-null arrays
# ---------------------------------------------------------------------------


class TestAllNullArrays:
    def test_all_null_int32(self):
        """Int32 array where every element is null."""
        array = pa.array([None, None, None, None], type=pa.int32())
        result = ArrowDigester.hash_array(array).hex()
        assert result == "00000104fd65cf73bc1d8e787a6940b749777eddb28285d7bfc90e832212afb6fdea65"

    def test_all_null_string(self):
        """LargeString array where every element is null."""
        array = pa.array([None, None, None], type=pa.large_utf8())
        result = ArrowDigester.hash_array(array).hex()
        assert result == "00000115a6af4eb6fdb3419afebadf58a9f184f0a1fffa09ffa56600237f501db71070"


# ---------------------------------------------------------------------------
# Boolean arrays
# ---------------------------------------------------------------------------


class TestBooleanArrays:
    def test_bool_17_elements(self):
        """17-element boolean array (multi-byte bitvec)."""
        array = pa.array(
            [
                True, False, True, True,
                None, False, True, False,
                True, None, True, False,
                True, True, False, None,
                True,
            ],
            type=pa.bool_(),
        )
        result = ArrowDigester.hash_array(array).hex()
        assert result == "000001f8ad377be621fd278f5590c7cab06ca42e2b4ed6867d363f9fbf28f6f3d7582a"


# ---------------------------------------------------------------------------
# Single-element arrays
# ---------------------------------------------------------------------------


class TestSingleElementArrays:
    def test_single_int64(self):
        """Single Int64 value: 9_999_999_999."""
        array = pa.array([9_999_999_999], type=pa.int64())
        result = ArrowDigester.hash_array(array).hex()
        assert result == "000001e1cb4b7821c4238f0c53befd313280ff45a74b301e7044957b01a701108c5b7f"

    def test_single_string(self):
        """Single LargeString value: 'hello world'."""
        array = pa.array(["hello world"], type=pa.large_utf8())
        result = ArrowDigester.hash_array(array).hex()
        assert result == "0000014db35cf6860dda66df959cd2b4882a4cddaa6d17e74cf389e71c5553e4cceadb"

    def test_single_bool_false(self):
        """Single Boolean value: false."""
        array = pa.array([False], type=pa.bool_())
        result = ArrowDigester.hash_array(array).hex()
        assert result == "00000117655fca3764c8082b61b9de7186594bdcc58b86934176bea4b12d95becc54df"


# ---------------------------------------------------------------------------
# Nullable struct via hash_array
# ---------------------------------------------------------------------------


class TestNullableStructHashArray:
    def test_nullable_struct_hash_array(self):
        """Struct with null buffer via hash_array — row 1 is null struct.

        Fields: a: Int32 non-null, b: LargeUtf8 non-null
        Data: [{a:10, b:'x'}, NULL, {a:30, b:'z'}]
        """
        a_arr = pa.array([10, 20, 30], type=pa.int32())
        b_arr = pa.array(["x", "y", "z"], type=pa.large_utf8())
        mask = pa.array([False, True, False], type=pa.bool_())
        fields = [
            pa.field("a", pa.int32(), nullable=False),
            pa.field("b", pa.large_utf8(), nullable=False),
        ]
        struct_array = pa.StructArray.from_arrays(
            [a_arr, b_arr],
            fields=fields,
            mask=mask,
        )
        result = ArrowDigester.hash_array(struct_array).hex()
        assert result == "0000011ea07bf87d5b03b132e46a169df25352cb2e3c5a5f8b067138e0bd2a2023e6d5"


# ---------------------------------------------------------------------------
# Three-level nested struct
# ---------------------------------------------------------------------------


class TestThreeLevelStruct:
    def test_three_level_struct_batch(self):
        """Three-level nested struct as record batch.

        top: Struct<x: Int32, mid: Struct<y: Int32, z: Int32>>
        Data: [{x:100, mid:{y:200, z:300}}]
        """
        inner_type = pa.struct([
            pa.field("y", pa.int32(), nullable=False),
            pa.field("z", pa.int32(), nullable=False),
        ])
        outer_type = pa.struct([
            pa.field("x", pa.int32(), nullable=False),
            pa.field("mid", inner_type, nullable=False),
        ])
        schema = pa.schema([pa.field("top", outer_type, nullable=False)])
        col = pa.array(
            [{"x": 100, "mid": {"y": 200, "z": 300}}],
            type=outer_type,
        )
        batch = pa.record_batch({"top": col}, schema=schema)
        result = ArrowDigester.hash_record_batch(batch).hex()
        assert result == "000001fdd123a2cceb977b1448eaba26039de58f3a782244bf1cff70a6742e2f6f220a"

    def test_three_level_struct_schema(self):
        """Schema hash for three-level nested struct."""
        inner_type = pa.struct([
            pa.field("y", pa.int32(), nullable=False),
            pa.field("z", pa.int32(), nullable=False),
        ])
        outer_type = pa.struct([
            pa.field("x", pa.int32(), nullable=False),
            pa.field("mid", inner_type, nullable=False),
        ])
        schema = pa.schema([pa.field("top", outer_type, nullable=False)])
        result = ArrowDigester.hash_schema(schema).hex()
        assert result == "000001f5e018be18625769644d2f10aa06d52a50df75ade8872248f7dc4b296ce997f7"

    def test_three_level_struct_hash_array(self):
        """Three-level struct via hash_array.

        Struct<inner: Struct<y: Int32, z: LargeUtf8>, x: Int32>
        Data: [{inner:{y:7,z:'a'}, x:5}, {inner:{y:8,z:'b'}, x:6}]
        """
        y_arr = pa.array([7, 8], type=pa.int32())
        z_arr = pa.array(["a", "b"], type=pa.large_utf8())
        inner_fields = [
            pa.field("y", pa.int32(), nullable=False),
            pa.field("z", pa.large_utf8(), nullable=False),
        ]
        inner = pa.StructArray.from_arrays(
            [y_arr, z_arr],
            fields=inner_fields,
        )
        x_arr = pa.array([5, 6], type=pa.int32())
        inner_type = pa.struct(inner_fields)
        outer_fields = [
            pa.field("inner", inner_type, nullable=False),
            pa.field("x", pa.int32(), nullable=False),
        ]
        outer = pa.StructArray.from_arrays(
            [inner, x_arr],
            fields=outer_fields,
        )
        result = ArrowDigester.hash_array(outer).hex()
        assert result == "0000011dc18344fc9e0c026561c3a38ca128e5afa90d7b66df2cffac51a18bf106d0d0"


# ---------------------------------------------------------------------------
# Struct with list child
# ---------------------------------------------------------------------------


class TestStructWithListChild:
    def test_struct_with_list_child_batch(self):
        """Record batch: struct with list child.

        record: Struct<id: Int32, tags: List<Int32 nullable>>
        Data: [{id:1, tags:[10,20]}, {id:2, tags:[30]}, {id:3, tags:null}]
        """
        ids = pa.array([1, 2, 3], type=pa.int32())
        tags = pa.array(
            [[10, 20], [30], None],
            type=pa.list_(pa.field("item", pa.int32(), nullable=True)),
        )
        struct_type = pa.struct([
            pa.field("id", pa.int32(), nullable=False),
            pa.field("tags", pa.list_(pa.field("item", pa.int32(), nullable=True)), nullable=True),
        ])
        struct_arr = pa.StructArray.from_arrays(
            [ids, tags],
            names=["id", "tags"],
        )
        schema = pa.schema([pa.field("record", struct_type, nullable=False)])
        batch = pa.record_batch([struct_arr], schema=schema)
        result = ArrowDigester.hash_record_batch(batch).hex()
        assert result == "000001e4173182e5596f68ac3a1013caea1fc4aa3003ebc5c434bdab8db83c9173635d"

    def test_struct_with_list_child_schema(self):
        """Schema hash for struct with list child."""
        struct_type = pa.struct([
            pa.field("id", pa.int32(), nullable=False),
            pa.field("tags", pa.list_(pa.field("item", pa.int32(), nullable=True)), nullable=True),
        ])
        schema = pa.schema([pa.field("record", struct_type, nullable=False)])
        result = ArrowDigester.hash_schema(schema).hex()
        assert result == "000001310788c527cc1f9b997d616ada011d9c3790a22d17dcc4e4cf0f043539f4c0ed"


# ---------------------------------------------------------------------------
# Nullable struct in record batch
# ---------------------------------------------------------------------------


class TestNullableStructBatch:
    def test_nullable_struct_batch(self):
        """Nullable struct in record batch — row 1 is null.

        s: Struct<a: Int32 non-null, b: Boolean non-null> nullable
        Data: [{a:1,b:true}, NULL, {a:3,b:true}]
        """
        a_arr = pa.array([1, 2, 3], type=pa.int32())
        b_arr = pa.array([True, False, True], type=pa.bool_())
        mask = pa.array([False, True, False], type=pa.bool_())
        struct_array = pa.StructArray.from_arrays(
            [a_arr, b_arr],
            names=["a", "b"],
            mask=mask,
        )
        struct_type = pa.struct([
            pa.field("a", pa.int32(), nullable=False),
            pa.field("b", pa.bool_(), nullable=False),
        ])
        schema = pa.schema([pa.field("s", struct_type, nullable=True)])
        batch = pa.record_batch([struct_array], schema=schema)
        result = ArrowDigester.hash_record_batch(batch).hex()
        assert result == "000001374a7e10ae3d1b9b46aa33f43988d5015290286e7236a3acbcd028462016e048"


# ---------------------------------------------------------------------------
# List<Struct> via hash_array
# ---------------------------------------------------------------------------


class TestListOfStruct:
    def test_list_of_struct_hash_array(self):
        """LargeList<Struct<id: Int32, name: LargeUtf8>> via hash_array.

        Row 0: [{id:1, name:'a'}, {id:2, name:'b'}]
        Row 1: [{id:3, name:'c'}, {id:4, name:'d'}]
        """
        ids = pa.array([1, 2, 3, 4], type=pa.int32())
        names = pa.array(["a", "b", "c", "d"], type=pa.large_utf8())
        struct_fields = [
            pa.field("id", pa.int32(), nullable=False),
            pa.field("name", pa.large_utf8(), nullable=False),
        ]
        struct_arr = pa.StructArray.from_arrays(
            [ids, names],
            fields=struct_fields,
        )
        inner_type = pa.struct([
            pa.field("id", pa.int32(), nullable=False),
            pa.field("name", pa.large_utf8(), nullable=False),
        ])
        inner_field = pa.field("item", inner_type, nullable=False)
        offsets = pa.array([0, 2, 4], type=pa.int64())
        list_array = pa.LargeListArray.from_arrays(offsets, struct_arr, type=pa.large_list(inner_field))
        result = ArrowDigester.hash_array(list_array).hex()
        assert result == "0000010d5f9a58c3122935886c0de076b8a90400dc9a1b3885154c734ab4616c52b626"

    def test_nullable_list_of_struct_hash_array(self):
        """Nullable LargeList<Struct> via hash_array — row 1 is null.

        Row 0: [{id:10, val:'p'}]
        Row 1: NULL
        Row 2: [{id:20, val:'q'}, {id:30, val:'r'}]
        """
        ids = pa.array([10, 20, 30], type=pa.int32())
        vals = pa.array(["p", "q", "r"], type=pa.large_utf8())
        struct_fields = [
            pa.field("id", pa.int32(), nullable=False),
            pa.field("val", pa.large_utf8(), nullable=False),
        ]
        struct_arr = pa.StructArray.from_arrays(
            [ids, vals],
            fields=struct_fields,
        )
        inner_type = pa.struct(struct_fields)
        inner_field = pa.field("item", inner_type, nullable=False)
        offsets = pa.array([0, 1, 1, 3], type=pa.int64())
        mask = pa.array([False, True, False], type=pa.bool_())
        list_array = pa.LargeListArray.from_arrays(offsets, struct_arr, type=pa.large_list(inner_field), mask=mask)
        result = ArrowDigester.hash_array(list_array).hex()
        assert result == "000001bb51997ac0fe67d4b08c5ced13b763c0ff5a532c9f9c8932fa2a4dd96fe57ea8"


# ---------------------------------------------------------------------------
# Non-nullable list
# ---------------------------------------------------------------------------


class TestNonNullableList:
    def test_list_non_nullable(self):
        """List<Int32> where all elements are present (no nulls at list or item level).

        Row 0: [1]
        Row 1: [2, 3]
        Row 2: [4, 5, 6]
        """
        array = pa.array(
            [[1], [2, 3], [4, 5, 6]],
            type=pa.list_(pa.field("item", pa.int32(), nullable=True)),
        )
        result = ArrowDigester.hash_array(array).hex()
        assert result == "00000150f18fb7ba1d34afe3f1b721a1ce10d1466dd55c228119449703ccf5ab771a5b"


# ---------------------------------------------------------------------------
# Struct with mixed types
# ---------------------------------------------------------------------------


class TestStructMixedTypes:
    def test_struct_mixed_types_hash_array(self):
        """Struct with int, string, bool, and list children via hash_array.

        Data: [{id:1, name:'Alice', active:true, scores:[90,85]},
               {id:2, name:'Bob', active:false, scores:[70]}]
        """
        id_arr = pa.array([1, 2], type=pa.int32())
        name_arr = pa.array(["Alice", "Bob"], type=pa.large_utf8())
        active_arr = pa.array([True, False], type=pa.bool_())
        scores_arr = pa.array(
            [[90, 85], [70]],
            type=pa.list_(pa.field("item", pa.int32(), nullable=True)),
        )
        struct_fields = [
            pa.field("id", pa.int32(), nullable=False),
            pa.field("name", pa.large_utf8(), nullable=False),
            pa.field("active", pa.bool_(), nullable=False),
            pa.field("scores", pa.list_(pa.field("item", pa.int32(), nullable=True)), nullable=False),
        ]
        struct_arr = pa.StructArray.from_arrays(
            [id_arr, name_arr, active_arr, scores_arr],
            fields=struct_fields,
        )
        result = ArrowDigester.hash_array(struct_arr).hex()
        assert result == "0000019f925992104e467b68e68e7dfa64ac7d39c82b002cb8c06f1c5bec19156107a3"


# ---------------------------------------------------------------------------
# Mixed struct + list record batch
# ---------------------------------------------------------------------------


class TestMixedStructListBatch:
    def test_mixed_struct_list_batch(self):
        """Record batch with id: Int64, meta: Struct, tags: LargeList<LargeUtf8>.

        Row 0: {id:100, meta:{key:'k1', value:10}, tags:['t1','t2']}
        Row 1: {id:200, meta:{key:'k2', value:null}, tags:['t3']}
        """
        schema = pa.schema([
            pa.field("id", pa.int64(), nullable=False),
            pa.field("meta", pa.struct([
                pa.field("key", pa.large_utf8(), nullable=False),
                pa.field("value", pa.int32(), nullable=True),
            ]), nullable=False),
            pa.field("tags", pa.large_list(
                pa.field("item", pa.large_utf8(), nullable=True)), nullable=True),
        ])

        id_arr = pa.array([100, 200], type=pa.int64())
        key_arr = pa.array(["k1", "k2"], type=pa.large_utf8())
        val_arr = pa.array([10, None], type=pa.int32())
        meta_arr = pa.StructArray.from_arrays(
            [key_arr, val_arr],
            names=["key", "value"],
        )

        tag_strings = pa.array(["t1", "t2", "t3"], type=pa.large_utf8())
        offsets = pa.array([0, 2, 3], type=pa.int64())
        tags_arr = pa.LargeListArray.from_arrays(
            offsets, tag_strings,
            type=pa.large_list(pa.field("item", pa.large_utf8(), nullable=True)),
        )

        batch = pa.record_batch([id_arr, meta_arr, tags_arr], schema=schema)
        result = ArrowDigester.hash_record_batch(batch).hex()
        assert result == "00000128fd142d16920be401eb33abf71143977164eb8952a7da20ae6673a8d1d3707a"

    def test_mixed_struct_list_schema(self):
        """Schema hash for mixed struct + list batch."""
        schema = pa.schema([
            pa.field("id", pa.int64(), nullable=False),
            pa.field("meta", pa.struct([
                pa.field("key", pa.large_utf8(), nullable=False),
                pa.field("value", pa.int32(), nullable=True),
            ]), nullable=False),
            pa.field("tags", pa.large_list(
                pa.field("item", pa.large_utf8(), nullable=True)), nullable=True),
        ])
        result = ArrowDigester.hash_schema(schema).hex()
        assert result == "0000011eb0482c51f8fb95dfae3c5ae83253a1e695dcf546fe5a3b6d75df172c5c2a45"


# ---------------------------------------------------------------------------
# Empty record batch (schema with 0 rows)
# ---------------------------------------------------------------------------


class TestEmptyBatchComplexSchema:
    def test_empty_batch_complex_schema(self):
        """Empty table hash (ArrowDigester(schema).finalize()) with complex schema."""
        schema = pa.schema([
            pa.field("x", pa.int32(), nullable=False),
            pa.field("y", pa.large_utf8(), nullable=True),
            pa.field("z", pa.struct([
                pa.field("a", pa.bool_(), nullable=False),
                pa.field("b", pa.float64(), nullable=True),
            ]), nullable=False),
        ])
        digester = ArrowDigester(schema)
        result = digester.finalize().hex()
        assert result == "000001837b0cc525983aca21f8979b3c2ed7c77d22728fb3b9a56df6ed4aee540dfa83"

    def test_empty_batch_complex_schema_hash(self):
        """Schema hash (hash_schema) for same complex schema."""
        schema = pa.schema([
            pa.field("x", pa.int32(), nullable=False),
            pa.field("y", pa.large_utf8(), nullable=True),
            pa.field("z", pa.struct([
                pa.field("a", pa.bool_(), nullable=False),
                pa.field("b", pa.float64(), nullable=True),
            ]), nullable=False),
        ])
        result = ArrowDigester.hash_schema(schema).hex()
        assert result == "00000194e104ebfea3ba38467c883d05a71884f8a1d0eace1c0dcfb00ab2d1203aa654"


# ---------------------------------------------------------------------------
# Batch with all-null column
# ---------------------------------------------------------------------------


class TestBatchAllNullColumn:
    def test_batch_all_null_column(self):
        """Record batch where one column is entirely null.

        id: [1, 2, 3], value: [null, null, null]
        """
        schema = pa.schema([
            pa.field("id", pa.int32(), nullable=False),
            pa.field("value", pa.large_utf8(), nullable=True),
        ])
        batch = pa.record_batch(
            {
                "id": pa.array([1, 2, 3], type=pa.int32()),
                "value": pa.array([None, None, None], type=pa.large_utf8()),
            },
            schema=schema,
        )
        result = ArrowDigester.hash_record_batch(batch).hex()
        assert result == "000001266d1fd64c44cf1f18ccc395bd2c712459e43807095d78115ff78497cd7ec494"


# ---------------------------------------------------------------------------
# Unicode strings
# ---------------------------------------------------------------------------


class TestUnicodeStrings:
    def test_unicode_string_array(self):
        """LargeString array with unicode characters."""
        array = pa.array(
            ["hello", "\u4e16\u754c", "\U0001f30d\U0001f30e\U0001f30f", None, "caf\u00e9"],
            type=pa.large_utf8(),
        )
        result = ArrowDigester.hash_array(array).hex()
        assert result == "000001d3f64ee0c7dac33e00445c2dd3edbb4b14cf61608682e4aae20d034dcaa3af40"


# ---------------------------------------------------------------------------
# Binary with varied sizes
# ---------------------------------------------------------------------------


class TestBinaryVariedSizes:
    def test_binary_varied_sizes(self):
        """Binary array with varied sizes including empty, null, and special bytes."""
        array = pa.array(
            [
                b"\x00\x01\x02\x03\x04\x05\x06\x07\x08\x09\x0a\x0b\x0c\x0d\x0e\x0f",
                b"",
                None,
                b"\xff",
                b"\x00",
            ],
            type=pa.binary(),
        )
        result = ArrowDigester.hash_array(array).hex()
        assert result == "0000010213a24d1014bb90e20f339fccab30ca699f2ca916d190f9a7f50077f5734b05"


# ---------------------------------------------------------------------------
# Struct field order independence
# ---------------------------------------------------------------------------


class TestStructFieldOrderIndependence:
    def test_struct_3field_order_independence(self):
        """Three-field struct: field order should not affect hash.

        Fields: a: Int32, b: LargeUtf8, c: Boolean
        Data: [{a:1,b:'x',c:true}, {a:2,b:'y',c:false}]
        """
        a = pa.array([1, 2], type=pa.int32())
        b = pa.array(["x", "y"], type=pa.large_utf8())
        c = pa.array([True, False], type=pa.bool_())

        fa = pa.field("a", pa.int32(), nullable=False)
        fb = pa.field("b", pa.large_utf8(), nullable=False)
        fc = pa.field("c", pa.bool_(), nullable=False)

        # Order: a, b, c
        s1 = pa.StructArray.from_arrays([a, b, c], fields=[fa, fb, fc])
        # Order: c, a, b
        s2 = pa.StructArray.from_arrays([c, a, b], fields=[fc, fa, fb])

        h1 = ArrowDigester.hash_array(s1).hex()
        h2 = ArrowDigester.hash_array(s2).hex()
        assert h1 == h2, "struct field order should not affect hash_array"
        assert h1 == "000001c3c2f4d6414b062973fa8277701f8e0689f7656405d03cd7fef1e1ef7c05ac25"


# ---------------------------------------------------------------------------
# Nested struct with nullable inner struct
# ---------------------------------------------------------------------------


class TestNestedNullableInnerStruct:
    def test_nested_nullable_inner_struct(self):
        """Outer struct with nullable inner struct — inner row 1 is null.

        Outer: Struct<a: Int32, inner: Struct<p: Int32, q: Int32> nullable>
        Data: [{a:10, inner:{p:1,q:4}}, {a:20, inner:NULL}, {a:30, inner:{p:3,q:6}}]
        """
        p = pa.array([1, 2, 3], type=pa.int32())
        q = pa.array([4, 5, 6], type=pa.int32())
        inner_mask = pa.array([False, True, False], type=pa.bool_())
        inner_fields = [
            pa.field("p", pa.int32(), nullable=False),
            pa.field("q", pa.int32(), nullable=False),
        ]
        inner = pa.StructArray.from_arrays(
            [p, q],
            fields=inner_fields,
            mask=inner_mask,
        )

        a = pa.array([10, 20, 30], type=pa.int32())
        inner_type = pa.struct(inner_fields)
        outer_fields = [
            pa.field("a", pa.int32(), nullable=False),
            pa.field("inner", inner_type, nullable=True),
        ]
        outer = pa.StructArray.from_arrays(
            [a, inner],
            fields=outer_fields,
        )
        result = ArrowDigester.hash_array(outer).hex()
        assert result == "000001d43e8fb43a96546aa158c8defdcf186e1f15e42cf12fb2439902374d320f503c"


# ---------------------------------------------------------------------------
# List of list (nested lists)
# ---------------------------------------------------------------------------


class TestListOfList:
    def test_list_of_list_hash_array(self):
        """LargeList<LargeList<Int32>> via hash_array.

        Row 0: [[1,2], [3]]
        Row 1: [[4,5], [6]]
        """
        inner_values = pa.array([1, 2, 3, 4, 5, 6], type=pa.int32())
        inner_offsets = pa.array([0, 2, 3, 5, 6], type=pa.int64())
        inner_field = pa.field("item", pa.int32(), nullable=False)
        inner_list = pa.LargeListArray.from_arrays(
            inner_offsets, inner_values,
            type=pa.large_list(inner_field),
        )
        outer_offsets = pa.array([0, 2, 4], type=pa.int64())
        outer_field = pa.field("item", pa.large_list(inner_field), nullable=False)
        outer_list = pa.LargeListArray.from_arrays(
            outer_offsets, inner_list,
            type=pa.large_list(outer_field),
        )
        result = ArrowDigester.hash_array(outer_list).hex()
        assert result == "0000010843e52522d6435df07140b616e2cce64d55fc0dd4ee798a1f8dab86edf7bedc"

    def test_list_of_list_batch(self):
        """Record batch with LargeList<LargeList<Int32>> column."""
        inner_values = pa.array([1, 2, 3, 4, 5, 6], type=pa.int32())
        inner_offsets = pa.array([0, 2, 3, 5, 6], type=pa.int64())
        inner_field = pa.field("item", pa.int32(), nullable=False)
        inner_list = pa.LargeListArray.from_arrays(
            inner_offsets, inner_values,
            type=pa.large_list(inner_field),
        )
        outer_offsets = pa.array([0, 2, 4], type=pa.int64())
        outer_field = pa.field("item", pa.large_list(inner_field), nullable=False)
        outer_list = pa.LargeListArray.from_arrays(
            outer_offsets, inner_list,
            type=pa.large_list(outer_field),
        )
        schema = pa.schema([pa.field("col", pa.large_list(outer_field), nullable=False)])
        batch = pa.record_batch([outer_list], schema=schema)
        result = ArrowDigester.hash_record_batch(batch).hex()
        assert result == "000001644acff58777778402bb96ee8aa5e8fac1b3ffe7c58fe3a27860d0e93581ed10"

    def test_list_of_list_schema(self):
        """Schema hash for list-of-list column."""
        inner_field = pa.field("item", pa.int32(), nullable=False)
        outer_field = pa.field("item", pa.large_list(inner_field), nullable=False)
        schema = pa.schema([pa.field("col", pa.large_list(outer_field), nullable=False)])
        result = ArrowDigester.hash_schema(schema).hex()
        assert result == "00000141016034ea375b62e02305da3756a08f63bdfa572a285858a15b1d6d0bb66330"


# ---------------------------------------------------------------------------
# Large schema (12 fields)
# ---------------------------------------------------------------------------


class TestLargeSchema:
    def test_large_schema_12_fields(self):
        """Schema hash for 12-field schema with mixed types."""
        schema = pa.schema([
            pa.field("f01", pa.int8(), nullable=False),
            pa.field("f02", pa.int16(), nullable=True),
            pa.field("f03", pa.int32(), nullable=False),
            pa.field("f04", pa.int64(), nullable=True),
            pa.field("f05", pa.float32(), nullable=False),
            pa.field("f06", pa.float64(), nullable=True),
            pa.field("f07", pa.bool_(), nullable=False),
            pa.field("f08", pa.large_utf8(), nullable=True),
            pa.field("f09", pa.large_binary(), nullable=False),
            pa.field("f10", pa.date32(), nullable=True),
            pa.field("f11", pa.struct([
                pa.field("nested_a", pa.int32(), nullable=False),
                pa.field("nested_b", pa.large_utf8(), nullable=True),
            ]), nullable=False),
            pa.field("f12", pa.large_list(
                pa.field("item", pa.int32(), nullable=True)), nullable=True),
        ])
        result = ArrowDigester.hash_schema(schema).hex()
        assert result == "000001d4b6edc1304b0e981460aefa31813af93631c46558569a5ba8d5613cdbd722bd"


# ---------------------------------------------------------------------------
# Schema with nested list-of-struct
# ---------------------------------------------------------------------------


class TestSchemaListOfStructWithList:
    def test_schema_list_of_struct_with_list(self):
        """Schema hash for LargeList<Struct<ts, msg, tags: LargeList<LargeUtf8>>>."""
        schema = pa.schema([
            pa.field("events", pa.large_list(
                pa.field("item", pa.struct([
                    pa.field("ts", pa.int64(), nullable=False),
                    pa.field("msg", pa.large_utf8(), nullable=True),
                    pa.field("tags", pa.large_list(
                        pa.field("item", pa.large_utf8(), nullable=False)),
                        nullable=True),
                ]), nullable=False)), nullable=True),
        ])
        result = ArrowDigester.hash_schema(schema).hex()
        assert result == "0000017f5258ff48e85b2a63cd1a29590ff3bfca39bf718365200ad74a8232bb654ec6"


# ---------------------------------------------------------------------------
# Deeply nested schema (4 levels)
# ---------------------------------------------------------------------------


class TestSchema4LevelNestedStruct:
    def test_schema_4_level_nested_struct(self):
        """Schema hash for 4-level nested struct: root.l1.l2.l3.leaf."""
        schema = pa.schema([
            pa.field("root", pa.struct([
                pa.field("l1", pa.struct([
                    pa.field("l2", pa.struct([
                        pa.field("l3", pa.struct([
                            pa.field("leaf", pa.int32(), nullable=False),
                        ]), nullable=False),
                    ]), nullable=False),
                ]), nullable=False),
            ]), nullable=False),
        ])
        result = ArrowDigester.hash_schema(schema).hex()
        assert result == "0000017e33cfc98b4338141e1d5dae0eef992e2c22ff89fbb9be054f7fae96f1b8577e"


# ---------------------------------------------------------------------------
# Nullable list-of-struct with nullable children
# ---------------------------------------------------------------------------


class TestNullableListStructNullableChildren:
    def test_nullable_list_struct_nullable_children_batch(self):
        """Record batch: nullable LargeList<Struct> with nullable children.

        items: LargeList<Struct<id: Int32, label: LargeUtf8 nullable>> nullable
        Row 0: [{id:1, label:'a'}, {id:2, label:null}]
        Row 1: NULL
        """
        ids = pa.array([1, 2, 3], type=pa.int32())
        labels = pa.array(["a", None, "c"], type=pa.large_utf8())
        struct_fields = [
            pa.field("id", pa.int32(), nullable=False),
            pa.field("label", pa.large_utf8(), nullable=True),
        ]
        struct_arr = pa.StructArray.from_arrays(
            [ids, labels],
            fields=struct_fields,
        )
        inner_type = pa.struct(struct_fields)
        inner_field = pa.field("item", inner_type, nullable=False)
        offsets = pa.array([0, 2, 3], type=pa.int64())
        mask = pa.array([False, True], type=pa.bool_())
        list_array = pa.LargeListArray.from_arrays(
            offsets, struct_arr,
            type=pa.large_list(inner_field),
            mask=mask,
        )
        schema = pa.schema([
            pa.field("items", pa.large_list(inner_field), nullable=True),
        ])
        batch = pa.record_batch([list_array], schema=schema)
        result = ArrowDigester.hash_record_batch(batch).hex()
        assert result == "0000018a03ac4fd279a17240cb084cef23b1dbda814a60dba70f2147cb468f9c44af96"


# ---------------------------------------------------------------------------
# Struct empty batch (schema only, struct fields)
# ---------------------------------------------------------------------------


class TestStructEmptyBatch:
    def test_struct_empty_batch(self):
        """Empty table hash with struct schema (0 rows)."""
        schema = pa.schema([
            pa.field("person", pa.struct([
                pa.field("name", pa.large_utf8(), nullable=False),
                pa.field("age", pa.int32(), nullable=False),
                pa.field("score", pa.float64(), nullable=False),
            ]), nullable=False),
        ])
        d = ArrowDigester(schema)
        result = d.finalize().hex()
        assert result == "00000120a2341ffaf6b2413ebdb36aa062aec7c9468e946cbbba353b1ab5c5f6d1a773"


# ---------------------------------------------------------------------------
# Multi-batch with struct column
# ---------------------------------------------------------------------------


class TestMultiBatchStruct:
    def test_multi_batch_struct(self):
        """Multi-batch streaming with struct column.

        Schema: s: Struct<x: Int32, y: Int32 nullable>
        Batch 1: [{x:1,y:10}, {x:2,y:null}]
        Batch 2: [{x:3,y:30}]
        """
        struct_type = pa.struct([
            pa.field("x", pa.int32(), nullable=False),
            pa.field("y", pa.int32(), nullable=True),
        ])
        schema = pa.schema([pa.field("s", struct_type, nullable=False)])

        s1 = pa.StructArray.from_arrays(
            [pa.array([1, 2], type=pa.int32()), pa.array([10, None], type=pa.int32())],
            names=["x", "y"],
        )
        batch1 = pa.record_batch([s1], schema=schema)

        s2 = pa.StructArray.from_arrays(
            [pa.array([3], type=pa.int32()), pa.array([30], type=pa.int32())],
            names=["x", "y"],
        )
        batch2 = pa.record_batch([s2], schema=schema)

        d = ArrowDigester(schema)
        d.update(batch1)
        d.update(batch2)
        result = d.finalize().hex()
        assert result == "000001d6b36c3858d63ed06e99de401b83e6255070da784f2d88c376b15e53bacbe86c"


# ---------------------------------------------------------------------------
# Multi-batch with list column
# ---------------------------------------------------------------------------


class TestMultiBatchList:
    def test_multi_batch_list(self):
        """Multi-batch streaming with LargeList<Int32> column.

        Batch 1: [[1,2], null]
        Batch 2: [[3,4,5]]
        """
        list_type = pa.large_list(pa.field("item", pa.int32(), nullable=True))
        schema = pa.schema([pa.field("items", list_type, nullable=True)])

        arr1 = pa.array(
            [[1, 2], None],
            type=list_type,
        )
        batch1 = pa.record_batch([arr1], schema=schema)

        arr2 = pa.array(
            [[3, 4, 5]],
            type=list_type,
        )
        batch2 = pa.record_batch([arr2], schema=schema)

        d = ArrowDigester(schema)
        d.update(batch1)
        d.update(batch2)
        result = d.finalize().hex()
        assert result == "000001fcf529d339593cb8537af4c1ed7d02aae69cfbbd2608b02e811035edb6ba4ec3"


# ---------------------------------------------------------------------------
# Float special values
# ---------------------------------------------------------------------------


# ---------------------------------------------------------------------------
# LargeList<Struct> with nullable vs non-nullable inner (item) field
#
# This exercises the structural-only BTreeMap entry created for List<Struct>.
# When inner_field.nullable=True the entry's BitVec is allocated but never
# populated (bit_count=0), so 8 zero bytes are prepended to the structural
# digest at finalisation.  Both Rust and Python handle this identically.
# Golden values verified via `cargo test list_struct_nullable_inner_field_parity`
# against the Rust starfix crate (PLT-1048).
# ---------------------------------------------------------------------------


class TestListStructNullableInnerField:
    """LargeList<Struct> — nullable vs non-nullable item field parity."""

    _ids = [1, 2, 3, 4]
    _labels = ["a", "b", "c", "d"]

    def _make_list_array(self, inner_nullable: bool) -> "pa.LargeListArray":
        ids = pa.array(self._ids, type=pa.int32())
        labels = pa.array(self._labels, type=pa.large_utf8())
        struct_fields = [
            pa.field("id", pa.int32(), nullable=False),
            pa.field("label", pa.large_utf8(), nullable=False),
        ]
        struct_arr = pa.StructArray.from_arrays(
            [ids, labels],
            fields=struct_fields,
        )
        inner_field = pa.field("item", pa.struct(struct_fields), nullable=inner_nullable)
        offsets = pa.array([0, 2, 4], type=pa.int64())
        return pa.LargeListArray.from_arrays(
            offsets,
            struct_arr,
            type=pa.large_list(inner_field),
        )

    def test_nullable_inner_field(self):
        """LargeList<Struct> with nullable=True item field.

        ids=[1,2,3,4], labels=['a','b','c','d'], offsets=[0,2,4]
        inner_field.nullable=True → structural-only entry has empty BitVec.
        Golden value confirmed against Rust (PLT-1048).
        """
        result = ArrowDigester.hash_array(self._make_list_array(inner_nullable=True)).hex()
        assert result == "0000012c2b1c1d5b4c3dc46ed5335834dbf0d7386c38e607a398a2897fdaf1df387e1c"

    def test_non_nullable_inner_field(self):
        """LargeList<Struct> with nullable=False item field.

        ids=[1,2,3,4], labels=['a','b','c','d'], offsets=[0,2,4]
        inner_field.nullable=False → no BitVec in structural-only entry.
        Golden value confirmed against Rust (PLT-1048).
        """
        result = ArrowDigester.hash_array(self._make_list_array(inner_nullable=False)).hex()
        assert result == "000001713fa0e500c9aebea61039b30371fd84c0dff8cd3b96b4266978658bf73e4d8c"

    def test_nullable_differs_from_non_nullable(self):
        """Nullable vs non-nullable inner field must produce different hashes."""
        hash_nullable = ArrowDigester.hash_array(self._make_list_array(inner_nullable=True)).hex()
        hash_not_nullable = ArrowDigester.hash_array(
            self._make_list_array(inner_nullable=False)
        ).hex()
        assert hash_nullable != hash_not_nullable, (
            "nullable and non-nullable item fields must produce distinct hashes"
        )


# ---------------------------------------------------------------------------
# Float special values
# ---------------------------------------------------------------------------


class TestFloatSpecialValues:
    def test_float64_special_values(self):
        """Float64 array with NaN, Inf, -Inf, 0.0, -0.0."""
        array = pa.array(
            [float("nan"), float("inf"), float("-inf"), 0.0, -0.0],
            type=pa.float64(),
        )
        result = ArrowDigester.hash_array(array).hex()
        assert result == "000001947acf002083724864f155cf2857b1c9107749f6c8bfec13ea84c20fa9f20b5a"


# ---------------------------------------------------------------------------
# Realistic batch (struct + list + scalar)
# ---------------------------------------------------------------------------


class TestRealisticBatch:
    def test_realistic_batch(self):
        """Realistic record batch: name, coords struct, readings list.

        name: ['A', null, 'C']
        coords: [{lat:40.7,lon:-74.0}, {lat:34.0,lon:-118.2}, {lat:51.5,lon:-0.1}]
        readings: [[1.0,2.0], null, [3.0,4.0,5.0]]
        """
        schema = pa.schema([
            pa.field("name", pa.large_utf8(), nullable=True),
            pa.field("coords", pa.struct([
                pa.field("lat", pa.float64(), nullable=False),
                pa.field("lon", pa.float64(), nullable=False),
            ]), nullable=False),
            pa.field("readings", pa.large_list(
                pa.field("item", pa.float32(), nullable=False)), nullable=True),
        ])

        name_arr = pa.array(["A", None, "C"], type=pa.large_utf8())
        lat_arr = pa.array([40.7, 34.0, 51.5], type=pa.float64())
        lon_arr = pa.array([-74.0, -118.2, -0.1], type=pa.float64())
        coords_arr = pa.StructArray.from_arrays(
            [lat_arr, lon_arr],
            names=["lat", "lon"],
        )

        reading_vals = pa.array([1.0, 2.0, 3.0, 4.0, 5.0], type=pa.float32())
        offsets = pa.array([0, 2, 2, 5], type=pa.int64())
        reading_mask = pa.array([False, True, False], type=pa.bool_())
        readings_arr = pa.LargeListArray.from_arrays(
            offsets, reading_vals,
            type=pa.large_list(pa.field("item", pa.float32(), nullable=False)),
            mask=reading_mask,
        )

        batch = pa.record_batch([name_arr, coords_arr, readings_arr], schema=schema)
        result = ArrowDigester.hash_record_batch(batch).hex()
        assert result == "0000010d6dda2bffa3477ea97d880b38e018f8ae083e3059db77876b48e9a14a8f17ac"

    def test_realistic_schema(self):
        """Schema hash for realistic batch."""
        schema = pa.schema([
            pa.field("name", pa.large_utf8(), nullable=True),
            pa.field("coords", pa.struct([
                pa.field("lat", pa.float64(), nullable=False),
                pa.field("lon", pa.float64(), nullable=False),
            ]), nullable=False),
            pa.field("readings", pa.large_list(
                pa.field("item", pa.float32(), nullable=False)), nullable=True),
        ])
        result = ArrowDigester.hash_schema(schema).hex()
        assert result == "0000011c85d47bb95c90c6aa05b8ab930cfbb369136fffd8e120cee5d94dd84ed3c356"
